Repository jenkins-x/homebrew-jx, pull requests merged in 2019-07, with the labels that each got.

#1477 fix: Update sha256 for 2.0.368
  Formula/jx.rb
Labels: size/XS

#1480 chore: Update sha256 to 2.0.371
  Formula/jx.rb
Labels: size/XS

#1482 feat: added in prebuild check to validate checksum
  jenkins-x.yml
  jx/scripts/test.sh
Labels: lgtm, size/S

#1485 fix: using the first value in the formula to check the sha against
  jx/scripts/test.sh
Labels: approved, size/XS

#1484 chore: add release notes
  jenkins-x.yml
  jx/scripts/changelog.sh
Labels: approved, size/S

#1487 fix: corrected script location for changelog.sh
  jenkins-x.yml
Labels: approved, size/XS

#1488 fix: made changelog executable
  jx/scripts/changelog.sh
Labels: approved, size/XS

#1519 chore: bump builders to avoid double tagging
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#1551 chore: added precommit configuration
  .pre-commit-config.yaml
  .secrets.baseline
Labels: approved, size/M

#1517 chore: Updating owners file
  OWNERS
Labels: approved, size/XS
